### ISSUE TITLE
Password is required, now password causes a crash

### ISSUE THREAD

**Issue by renssies** [maximkulkin/esp-wifi-config#1]
Currently the code has no protection against not entering a password. for `wifi_config_init`. But having no password will cause the code to crash.

**Comment by maximkulkin** [comment]
Is it still a thing or solution was to erase flash?

**Comment by renssies** [comment]
No this is still a thing, even if you erase flash. It crashes on line 495.

**Comment by maximkulkin** [comment]
I will check that. As a workaround I suggest you use a password.

**Comment by renssies** [comment]
I did test it with a password and that does work

**Comment by maximkulkin** [comment]
Fixed compilation issues and tested passwordless setup. Also, you can find an example of using this lib in esp-homekit-demo repository.
