### ISSUE TITLE
SSID with special character

### ISSUE THREAD

**Issue by Rthierry** [maximkulkin/esp-wifi-config#10]
Hello,

If the ssid contain a '&' within the name the configuration fail because of the post form will fill the value with &amp;so the ssid is wrong and unable to connect to the wifi network.

<img width="985" alt="ssid bug" src="https://user-images.githubusercontent.com/5621591/50452699-edde4c80-093b-11e9-90bf-441cab47a786.png">

As a workaround, you can post the rights values with postman for example.
in the body x-www-form-urlencoded with ssid and password keys.

**Comment by milliamp** [comment]
It looks like this should be a very quick fix but it might take me a while before I can set up a wifi SSID with an '&' in it to test this. I'll write a pull request up for this fix once we know if it works or not. 

I assume, (without testing) that the following change in '`content/index.html`' should fix this up.
![image](https://user-images.githubusercontent.com/2096749/50515618-b2de4380-0b0a-11e9-8ec2-eca109290856.png)

**Comment by maximkulkin** [comment]
Should be fixed now. Thanks @milliamp for providing a fix.
