### ISSUE TITLE
Wifi Client mode >> Wifi AP mode >> Wifi Client mode

### ISSUE THREAD

**Issue by peros550** [maximkulkin/esp-wifi-config#11]
Hi Maxim, 

as far as I understand, when an already paired device restarts, it tries to reconnect to the last known Wifi SSID for xxx seconds (DWIFI_CONFIG_CONNECT_TIMEOUT=xxx) and then if it does not succeed it turns into AP mode.

I was wondering if it's possible to create a timeout for the period operating in AP mode. For example a device could stay in AP and wait for any connections and then if nothing happens for i.e. 5-10 minutes it would try to reconnect again to the last known Wifi network.

In the current implementation if for whatsoever reason the device does not connect to Wifi SSID, it turns into AP mode and stays there until you physically disconnect it from the mains. Having to power reset a device in such situation is sometimes tricky or difficult (i.e. in cases that a device is installed into an electrical box etc).

Similar discussions here: https://github.com/RavenSystem/esp-homekit-devices/issues/169

and here https://github.com/RavenSystem/esp-homekit-devices/issues/164

Thank you,
Yiannis

**Comment by maximkulkin** [comment]
Yeah, that make sense, I will look into it.

**Comment by AramVartanyan** [comment]
In some specific circumstances the ESP stops trying to reconnect and the code leads it to AP mode.
It is usually after power outage. (Or also if a network AP repeater is involved and the router is restarted.) The router is not as fast as the ESP at startup. During the "no network" period it goes very fast to AP mode.

While I was trying to understand the mechanism of WiFi-config, I suspected that the real issue is behind the sdk wifi station auto connect function.
But there must be a good solution.

**Comment by AramVartanyan** [comment]
Actually I found out that the auto connect function is still running in the background, and the ESP goes to AP mode.
When the router is ready and the WiFi is available the ESP is getting connected and in the same time still shows in AP mode and the HomeKit server is not started.
Here are some logs:

no Network found, reconnect after 1s
reconnect
scandone
no Network found, reconnect after 1s
reconnect
scandone
scandone
reconnect
scandone
add 0
aid 1
cnt

connected with Network, channel 6
dhcp client start...
ip:172.20.10.11,mask:255.255.255.240,gw:172.20.10.1
scandone
station: 58:b0:35:7f:60:d5 join, AID = 1
wifi_config: http_task: Got 64 incomming data
!!! wifi_config: Unknown endpoint: GET /hotspot-detect.html
wifi_config: http_task: Got 64 incomming data
wifi_config: http_task: Got 3 incomming data
wifi_config: wifi_config_server_on_message_complete: Unknown endpoint
wifi_config: client_send_redirect: Redirecting to http://192.168.4.1/settings
wifi_config: Client disconnected
wifi_config: http_task: Got 64 incomming data
wifi_config: http_task: Got 64 incomming data
wifi_config: http_task: Got 64 incomming data
wifi_config: http_task: Got 64 incomming data
wifi_config: http_task: Got 64 incomming data
wifi_config: http_task: Got 10 incomming data
wifi_config: Client disconnected
wifi_config: http_task: Got 64 incomming data
!!! wifi_config: Unknown endpoint: GET /favicon.ico
...

**Comment by erpayo** [comment]
Hi, my proposed solution:

In wifi_config.c remove the call to sdk_os_timer_disarm in line 620

By calling timer disarm the function wifi_config_sta_connect_timeout_callback is not called again. By removing the call to timer_disarm the function will be called periodically to check if the client connection has been made while the ap mode was on. Once the WiFi client connection to the configured network has been made the ap mode is stopped and the on_wifi_ready() callback is called

**Comment by pcsaito** [comment]
I have just flashed one sonoff here with a lot higher WIFI_CONFIG_CONNECT_TIMEOUT to solve the problem I have with power failures: my router need a lot more time to start than the ESP, so it never connects. I usually have to disarm a circuit breaker to make it connect or do the softAp config again...

I raised the WIFI_CONFIG_CONNECT_TIMEOUT to 300000 and now the router have enough time to return online, I think 15 seconds is not sufficient time to a number of routers to boot up.

Of course an reconnect routine would make it even more resilient...

**Comment by maximkulkin** [comment]
Implemented new WiFi state monitoring. Should automatically reconnect to known WiFi, exposing reconfiguration interface in meantime.

**Comment by peros550** [comment]
Many thanks!!!!!
