### ISSUE TITLE
Config not being applied

### ISSUE THREAD

**Issue by trakais** [maximkulkin/esp-wifi-config#12]
Not sure where to ask, so will try here. I did get the wifi config popup, selected my AP in the list, entered the password and clicked "join", but the config doesn't seem to be applied, as the Sonoff AP is still visible. This is what I see in the console log: 

 >>> wifi_config: http_task: Got 64 incomming data
 >>> wifi_config: http_task: Got 16 incomming data
 >>> wifi_config: wifi_config_server_on_settings_update: Update settings, body =  ssid=dodies&password=mypasswordhere
 >>> wifi_config: wifi_config_station_connect: No configuration found
 >>> wifi_config: Client disconnected
 scandone
 scandone

What am I doing wrong?

**Comment by maximkulkin** [comment]
I will add some more logging to understand what has happened. In meantime, try erasing flash and re-flash again: people say that sysparams (subsystem that handles configuration storage) might fail if corresponding flash area is not properly initialized (not empty).

**Comment by mcrobiej** [comment]
I get the same error - but I get it as part of the initial setup of Sonoff-Homekit .

**Comment by trakais** [comment]
Thanks, you were right, Maxim. I did a couple of flash processes and then it worked. Sonoff works great now!

**Comment by LW-Ho** [comment]
Thanks, first erase flash, then re-flash the Sonoff just working.
