### ISSUE TITLE
hidden network

### ISSUE THREAD

**Issue by lukasa1993** [maximkulkin/esp-wifi-config#14]
any way connecting to hidden ssid with

```
wifi_config_init("my-accessory", "my-password", on_wifi_ready);
```

**Comment by maximkulkin** [comment]
Oh, it is not implemented at the moment, but you can do a quick fix to enable that. Just remove `style="display: none;"` from [this line](https://github.com/maximkulkin/esp-wifi-config/blob/master/content/index.html#L67) and [this line](https://github.com/maximkulkin/esp-wifi-config/blob/master/content/index.html#L72) and recompile project.

**Comment by maximkulkin** [comment]
Just pushed support for hidden networks. It adds an "Other" option at the bottom of networks list, choosing which will show SSID entry box.
