### ISSUE TITLE
Question: local images

### ISSUE THREAD

**Issue by HomeKidd** [maximkulkin/esp-wifi-config#16]
Hi! Is it possible to upload .png images that shows up when the wi-fi config page loads? 
I want to show my logo inside the captive portal.
Is it possible? If yes, any example avaible?

Thanks

**Comment by maximkulkin** [comment]
I think you can modify index.html to embed image right inside html page using [data URIs](https://css-tricks.com/data-uris).

**Comment by HomeKidd** [comment]
Yep, i’ve tried to modify index.html but doesnt work, but I’ve forget to try the URI method! 🙄
Thanks a lot! I’ll try this!😁
