### ISSUE TITLE
White screen after selecting wifi

### ISSUE THREAD

**Issue by pocketscience** [maximkulkin/esp-wifi-config#25]
There seems to be an issue on current iOS, and even macOS, where after selecting your wifi AP and clicking the Join button you get a white screen and it never goes away. Highly repeatable.

**Comment by d4rkmen** [comment]
@pocketscience never faced the issue

**Comment by pocketscience** [comment]
OK... like I said though - highly repeatable across multiple wifi AP's and devices. I know of a bunch of others who've hit the same issue - specifically when using https://github.com/Gruppio/Sonoff-Homekit. Not sure if it's using an older version of wifi-config, but the author is AWOL and isn't even responding to his "buy me a coffee" supporters (ie pay $5 and get nothing).. :/

**Comment by pocketscience** [comment]
Just ran a diff - same wifi-config source in use

**Comment by maximkulkin** [comment]
The behavior of captive portal UI is mysterious and sometimes it does behave like that. I haven't seen any specs on that technology, so it's hard to say who's to blame. HOWEVER, even though you get an empty page, the thing actually works: it shuts down it's own AP and starts connecting to specified AP.

**Comment by pocketscience** [comment]
Hmm, ok - I'll have to check that. I guess most people, myself included, assume that if the wifi setup doesn't complete then it's not ready to try adding the accessory in Home.

**Comment by maximkulkin** [comment]
I assume this has been resolved
