### ISSUE TITLE
Memory leak during AP mode

### ISSUE THREAD

**Issue by renssies** [maximkulkin/esp-wifi-config#3]
There seems to be a memory leak somewhere when the `esp-wifi-config` goes into AP mode. When combining it with `esp-homekit`, this causes the SRP shared secret to fail. 

The free heap before the shared secret fails AP mode is `21888`
The free heap before the shared secret is created without AP Mode is `30324`

**Comment by maximkulkin** [comment]
I believe, this is no longer the case. If not, feel free to reopen.
