### ISSUE TITLE
How different is this from WiFiManager?

### ISSUE THREAD

**Issue by cottsak** [maximkulkin/esp-wifi-config#5]
And does it support https://github.com/tzapu/WiFiManager#custom-parameters ?

**Comment by maximkulkin** [comment]
This library is a very lightweight minimal configuration way to configure network connectivity for yor accessory.

**Comment by cottsak** [comment]
Thanks.

Does it support a network scan? Or must the user specify the SSID?

**Comment by maximkulkin** [comment]
Yes, it scans and shows networks (and it does not support manually entering SSID)
