### ISSUE TITLE
Does this work on ESP32?

### ISSUE THREAD

**Issue by bwjohns4** [maximkulkin/esp-wifi-config#6]
I am quite a newbie with building and modifying projects of this size, but would like to know if I can use this directly with the homekit-demo examples/esp32/led in the same way that it was used in sonoffbasic. Will the button.c work as well? How hardware specific is the code between esp8266 and esp32? Can I just copy and modify the code from within the esp32 directory with the same makefile and it will build as expected?

**Comment by maximkulkin** [comment]
No, you can not use it as-is with ESP32 as some APIs have changed.
