### ISSUE TITLE
Add disconnect callback?

### ISSUE THREAD

**Issue by 01matrix01** [maximkulkin/esp-wifi-config#8]
Hi Maxim,
this light version of WifiManager is amazing, but it is possible to have on your wifi_config_init() a callback also for wifi disconnect event?

Thanks in advance

**Comment by peros550** [comment]
Sorry for asking and If you don't mind, why would you need a callback for disconnect?

**Comment by 01matrix01** [comment]
Hi peros550,
for example, you can use led_write to make led blinking until password is saved and until the board is not connected to wifi, after that you can put led to solid ON or OFF in “void on_wifi_ready()”

So suppose to be ON, if I power off my router the led is always on because there is no callback that tell me wifi lost.

Also for MQTT purpose, to try reconnection to MQTT Server only if wifi is ok

**Comment by peros550** [comment]
@01matrix01 your examples make perfect sense. 
I hope this request will be considered by the author!

**Comment by peros550** [comment]
@maximkulkin Do you thing a callback / event when wifi changing status (i.e. on connect, on disconnect ) is possible though this library? Or this is not possible due limitation in esp-open-rtos?

**Comment by maximkulkin** [comment]
Added new callback - on_wifi_event - which you can use if you substitute `wifi_config_init()` with `wifi_config_init2()`. New callback accepts event type parameter. Supported events are WIFI_CONFIG_CONNECTED and WIFI_CONFIG_DISCONNECTED.

**Comment by peros550** [comment]
> New callback accepts even type parameter.

Hi Maxim, 

if you find some free time, would it be possible to provide an example of a typed parameter and its use?

Thank you,

**Comment by maximkulkin** [comment]
```c
void on_wifi_event(wifi_event_t event) {
    switch (event) {
        case WIFI_CONFIG_CONNECTED:
            printf("Connected\n");
            homekit_server_init(&config);
            break;
        case WIFI_CONFIG_DISCONNECTED:
            printf("Disconnected\n");
            break;
    }
}

wifi_config_init2("my-accessory-wifi", "secret", on_wifi_event);
```

**Comment by peros550** [comment]
Many thanks!
